/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 scene.gltf 
Author: みそ太郎 (https://sketchfab.com/nama_140)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-origingundamthe-origin-ver-b1fbcc97214a431bbc024f7bc929c41a
Title: ガンダム（THE ORIGIN版)/Gundam(THE ORIGIN ver)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function GundamOriginal(props) {
  const group = React.useRef()
  const { scene } = useGLTF('./models/the_origingundamthe_origin_ver/scene.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials, animations } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={1.349}>
          <group name="2a10103a3e4248148a52fc186392e831fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="���������������THE_ORIGIN���)_arm" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_71" position={[-119.308, 170.005, -18.497]} rotation={[-Math.PI / 2, 0, 0]} scale={24.188} />
                    <group name="Object_73" position={[0, 170.841, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <skinnedMesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials.material} skeleton={nodes.Object_72.skeleton} />
                    <skinnedMesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials.GUNDAM} skeleton={nodes.Object_74.skeleton} />
                  </group>
                </group>
                <group name="���������001" position={[-119.308, 170.005, -18.497]} rotation={[-Math.PI / 2, 0, 0]} scale={24.188} />
                <group name="01-���001" position={[0, 170.841, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
