/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 scene.gltf 
Author: oiopu (https://sketchfab.com/oiopu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gundam-phenex-44d46cc7aeb64ea59798c603c968dabc
Title: Gundam Phenex
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function GundamPhenex(props) {
  const { nodes, materials } = useGLTF('/models/gundam_phenex/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Material2.geometry} material={materials.material_12} />
        <mesh geometry={nodes.Material3.geometry} material={materials.material_11} />
        <mesh geometry={nodes.Material3_1.geometry} material={materials.Charcoal} />
        <mesh geometry={nodes.Material3_2.geometry} material={materials['96_96_96']} />
        <mesh geometry={nodes.Material2_1.geometry} material={materials.Black} />
        <mesh geometry={nodes.Material3_3.geometry} material={materials.LightGray} />
        <mesh geometry={nodes.Material2_2.geometry} material={materials.material_5} />
        <mesh geometry={nodes.Material3_4.geometry} material={materials.material_6} />
        <mesh geometry={nodes.Material2_3.geometry} material={materials.material_9} />
        <mesh geometry={nodes.Material3_5.geometry} material={materials.material_1} />
        <lineSegments geometry={nodes.Material5.geometry} material={materials.edge_color404040255} />
        <lineSegments geometry={nodes.Material4.geometry} material={materials.edge_color646464255} />
        <mesh geometry={nodes.Material2_4.geometry} material={materials.Color_B24} />
        <mesh geometry={nodes.Material3_6.geometry} material={materials.Black_Out} />
        <mesh geometry={nodes.Material3_7.geometry} material={materials.Color_008} />
        <mesh geometry={nodes.Material3_8.geometry} material={materials.Color_G24} />
        <mesh geometry={nodes.Material3_9.geometry} material={materials.Color_G21} />
        <lineSegments geometry={nodes.Material5_1.geometry} material={materials.edge_color564542255} />
        <lineSegments geometry={nodes.Material6.geometry} material={materials.edge_color172233255} />
        <mesh geometry={nodes.Material2_5.geometry} material={materials.Color_007} />
        <mesh geometry={nodes.Material2_6.geometry} material={materials.Color_005} />
        <mesh geometry={nodes.Material3_10.geometry} material={materials.Color_006} />
        <mesh geometry={nodes.Material3_11.geometry} material={materials.Color_009_2} />
        <mesh geometry={nodes.Material2_7.geometry} material={materials.Color_B18} />
        <lineSegments geometry={nodes.Material5_2.geometry} material={materials.edge_color303030255} />
        <lineSegments geometry={nodes.Material3_12.geometry} material={materials.edge_color636363255} />
        <mesh geometry={nodes.Material3_13.geometry} material={materials.material_14} />
        <mesh geometry={nodes.Material2_8.geometry} material={materials.material_13} />
        <lineSegments geometry={nodes.Material5_3.geometry} material={materials.edge_color969696255} />
        <lineSegments geometry={nodes.Material3_14.geometry} material={materials.edge_color02550255} />
        <mesh geometry={nodes.Material2_9.geometry} material={materials.Beige_1} />
        <mesh geometry={nodes.Material3_15.geometry} material={materials.jean_blue} />
        <lineSegments geometry={nodes.Material5_4.geometry} material={materials.edge_color818181255} />
        <mesh geometry={nodes.Material3_16.geometry} material={materials['0135_DarkGray']} />
        <mesh geometry={nodes.Material3_17.geometry} material={materials.material_21} />
        <mesh geometry={nodes.Material2_10.geometry} material={materials.material} />
        <mesh geometry={nodes.Material3_18.geometry} material={materials.material_0} />
        <mesh geometry={nodes.Material2_11.geometry} material={materials.material_7} />
        <mesh geometry={nodes.Material3_19.geometry} material={materials.material_22} />
        <mesh geometry={nodes.Material3_20.geometry} material={materials.material_8} />
        <mesh geometry={nodes.Material3_21.geometry} material={materials.LightGray_1} />
        <mesh geometry={nodes.Material2_12.geometry} material={materials.Derrick_Shoes} />
        <mesh geometry={nodes.Material2_13.geometry} material={materials.Derrick_Shirt} />
        <mesh geometry={nodes.Material2_14.geometry} material={materials.Derrick_Hair} />
        <mesh geometry={nodes.Material2_15.geometry} material={materials.Derrick_Pager} />
        <mesh geometry={nodes.Material2_16.geometry} material={materials.Derrick_Sweater} />
        <mesh geometry={nodes.Material2_17.geometry} material={materials['Derrick_T-shirt']} />
        <mesh geometry={nodes.Material2_18.geometry} material={materials.Derrick_Pants} />
        <mesh geometry={nodes.Material2_19.geometry} material={materials.Derrick} />
        <lineSegments geometry={nodes.Material3_22.geometry} material={materials.edge_color226226226255} />
        <lineSegments geometry={nodes.Material2_20.geometry} material={materials.edge_color2551700255} />
        <lineSegments geometry={nodes.Material4_1.geometry} material={materials.edge_color2551700255} />
        <lineSegments geometry={nodes.Material2_21.geometry} material={materials.edge_color383844255} />
        <lineSegments geometry={nodes.Material2_22.geometry} material={materials.edge_color00255255} />
        <lineSegments geometry={nodes.Material2_23.geometry} material={materials.edge_color000255} />
        <lineSegments geometry={nodes.Material3_23.geometry} material={materials.edge_color353535255} />
        <lineSegments geometry={nodes.Material2_24.geometry} material={materials.edge_color0053255} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/gundam_phenex/scene.gltf')
